apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-preparation
  labels:
    app: food-preparation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-preparation
  template:
    metadata:
      labels:
        app: food-preparation
    spec:
      containers:
        - name: food-preparation
          image: "username/food-preparation:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
